### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-run-bike-and-hike.tm2#6]
1. Fix issues caused by latest Mapnik update, including:

  - City with dots styling
  - POI icons

2. Update to take advantage of latest Mapnik features.

3. Update to latest data sources.

**Comment by MateoV** [comment]
>Update to latest data sources.

Just flagging to include `mapbox.mapbox-terrain-v2` in this.

**Comment by ajashton** [comment]
> Update to latest data sources

This has happened already https://github.com/mapbox/mapbox-studio-run-bike-and-hike.tm2/blob/27db90b0e30d1eeccdd33dd86b6736b08f3ef602/project.yml#L49

Curious about any further details about 1 and 2 and whether we hit some/all in v2.0.0: https://github.com/mapbox/mapbox-studio-run-bike-and-hike.tm2/compare/v1.0.2...v2.0.0

**Comment by nickidlugash** [comment]
These still need to happen, but I'd like to hit these myself when I get back.

**Comment by nickidlugash** [comment]
Forgot to close this – made these changes via f6b5662808871d3c37bc0c50f8a8f3517ba44b38
