### ISSUE TITLE
Height labels are wrong in Brazil

### ISSUE THREAD

**Issue by miguelpeixe** [mapbox/mapbox-studio-run-bike-and-hike.tm2#7]
As you can see on the image below, the top of the Pão de Açucar is labeled 0 meters

![paodeacucar](https://cloud.githubusercontent.com/assets/820752/6311200/6564a50a-b946-11e4-9c3b-2da2279a32bd.png)

**Comment by MateoV** [comment]
Thanks. This will be fixed when we update to `mapbox.mapbox-terrain-v2`. Ref #6
